backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "Movie Post" 
    label: "Movie Post"
    folder: "src/movie-post"
    create: true
    slug: "{{filetitle}}"
    fields:
   
    - { label: "Body", name: "body", widget: "markdown", required:false}
  - name: "blog" 
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{filetitle}}"
    fields:
    - { label: "Body", name: "body", widget: "markdown", required:false}
