backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "Movie Post" 
    label: "Movie Post"
    folder: "src/movie-post"
    create: true
    slug: "{{filetitle}}"
    fields:
    - { label: "Title For Page", name: "title", widget: "string" }
    - { label: "Title For File", name: "filetitle", widget: "string" }
    - { label: "Author", name: "author", widget: "string" }
    - { label: "Movie Release Date", name: "releaseDate", widget: "string" }
    - { label: "Movie Name", name: "movieName", widget: "string" }
    - { label: "Max Quality", name: "maxQuality", widget: "string" }
    - { label: "Languages", name: "languageAvailable", widget:"string", required:false}
    - { label: "Category", name: "category" , widget: "string" } 
    - { label: "Tags", name: "tags", widget: "list", default: ["posts","movie","another-tag-here"]}
    - { label: "Movie Geners",
        name: "geners" ,
        widget: "select" ,     
        options: [ "Action" , 
                   "Comedy" ,
                   "Fiction" , 
                   "Drama" , 
                   "Fantasy" , 
                   "Horror" , 
                   "Mystery" ,
                   "Romance" ,
                   "Thriller" 
                   ]
                } 
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Save as Draft", name: "draft", widget: "boolean", required:false, default:true}
    - { label: "Tags", name: "tagsmovie", widget: "list", default: ["post","movie","another-tag-here"]}
    - { label: "Featured Image", name: "image", widget: "image", required:false}
    - { label: "Image Caption", name: "imageAlt", widget: "string", required:false}
    - { label: "Movie Link", name: "movieLink", widget: "string", required:false}
    - { label: "Body", name: "body", widget: "markdown", required:false}
  - name: "blog" 
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{filetitle}}"
    fields:
    - { label: "Title For Page", name: "title", widget: "string" }
    - { label: "Title For File", name: "filetitle", widget: "string" }
    - { label: "Author", name: "author", widget: "string" }
    - { label: "Category",
        name: "category" ,
        widget: "select" , 
        options: [ "fashion" , 
        "gaming" , "health" , 
        "movie" , "music" , 
        "news" , "personal-development" ,
        "technology" , "travelling" ] } 
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Save as Draft", name: "draft", widget: "boolean", required:false, default:true}
    - { label: "Tags", name: "tags", widget: "list", default: ["posts","another-tag-here"]}
    - { label: "Featured Image", name: "image", widget: "image", required:false}
    - { label: "Image Caption", name: "imageAlt", widget: "string", required:false}
    - { label: "Body", name: "body", widget: "markdown", required:false}
