backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog" 
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{filetitle}}"
    fields:
    - { label: "Title For Page", name: "title", widget: "string" }
    - { label: "Title For File", name: "filetitle", widget: "string" }
    - { label: "Author", name: "author", widget: "string" }
    - { label: "Category",
        name: "category" ,
        widget: "select" , 
        options: [ "fashion" , 
        "gaming" , "health" , 
        "movie" , "music" , 
        "news" , "personal-development" ,
        "technology" , "travelling" ] } 
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Tags", name: "tags", widget: "list", default: ["posts","another-tag-here"]}
    - { label: "Featured Image", name: "image", widget: "image" }
    - { label: "Image Caption", name: "imageAlt", widget: "string" } 
    - { label: "Body", name: "body", widget: "markdown" }
